### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by eirnym** [michaelruocco/jackson-json-api#2]
Thank you for your library, could you please, explicitly specify a licence?

**Comment by michaelruocco** [comment]
Sure, I've got a bunch of other CI improvements to apply to this repo so I will include adding a license as well, I will probably do it this weekend.

**Comment by michaelruocco** [comment]
I had some time this morning so this is all done now.

**Comment by eirnym** [comment]
Thank you for clearance of this uncertainty (as different repo aggregators showed different licences, mostly permissive like BSD-2).

I had a hope that I'd be able to use it in my project as your library is the best of this kind. GPL is the only licence I can't use at all unlike all others including "GPL with classpath exception". Also I have to watch out all libraries could use your library as well.

**Comment by michaelruocco** [comment]
I just picked one from this list here? https://choosealicense.com/

Are you intending to create closed source code using this library?

**Comment by eirnym** [comment]
Yes, I'm intended to create a commercial closed source code project using this library if it'd be possible. Library under GPL-xx  licence requires whole project to be under GPL as well. If you want this library have a copyleft licence and this library be usable in projects with other types of licence, then LGPL (any version) or a "GPL with classpath exception" (this is a kinda weird licence, but still exists) will be sufficient for this purpose. With those licences all changes to this library still have to be open with the same licence, and it's possible to use it in any kind of project, not only under GPL.

**Comment by michaelruocco** [comment]
So I guess you would need the repo to use a different licence like MIT instead? I generally put my code out to be used for open source purposes normally, I've never really needed to bother with licenses etc before so I am not that up to speed on it. Ill do some more reading.

**Comment by eirnym** [comment]
Thank you, your projects are good.

MIT or other permissive licence is the best choice for me

To check if a library licence is compatible, I use a web service https://tldrlegal.com to quick check the information and read a text.

**Comment by michaelruocco** [comment]
Okay sure, I'll take a look tomorrow. Thanks.

**Comment by michaelruocco** [comment]
Updated to MIT license instead now.

**Comment by eirnym** [comment]
thank you a lot for your kindness. This will boost my project a lot
